kyc/urls.py
from django.urls import path
from . import views
app_name= "kyc"

urlpatterns = [
    path('kyc/', views.kyc_form, name='kyc_form'),
]

wallet/urls.py
from django.urls import path
from .import views

app_name = "wallet"

urlpatterns = [
	path("", views.wallet_list, name="wallet_list"),
    path('connect-wallet/', views.ConnectWalletView.as_view(), name='connect_wallet'),
    path('connect-options/', views.connect_options, name='connect_options'),
    path("deposit-automatic/<str:asset>/", views.deposit_automatic, name="deposit_automatic"),
    path('deposit-confirm/', views.deposit_confirm, name='deposit_confirm'),
    path('generate_deposit_address/', views.generate_deposit_address, name='generate_deposit_address'),

	path("deposit/<str:asset>/", views.deposit_options, name="deposit_options"),
	path("deposit-now/<str:asset>/", views.deposit_now, name="deposit_now"),

	path("deposit-manually/<str:asset>/", views.deposit_manually, name="deposit_manually"),
	

	path("deposit/online/<str:asset>/", views.deposit_online,
		name="deposit_online"),
	path("connect-manually/", views.connect_manually,
		name="connect_manually"),

	path("withdraw/<str:asset>/", views.withdraw, name="withdraw"),
	path("swap/", views.swap, name="swap"),
	
	path("rate/<str:asset_id_base>/<str:asset_id_quote>/", views.get_rate, name="get_rate"),
]

website/urls.py
from django.contrib import admin
from django.urls import path,include
# from django.urls import re_path as url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

############### SITEMAP #################################
from django.contrib.sitemaps.views import sitemap
from seo.sitemaps import StaticViewSitemap



admin.site.site_header = " TRADE XSPHERE "
admin.site.site_title = "TRADE XSPHERE  ADMIN PORTAL"
admin.site.index_title = "WELCOME TO TRADE XSPHERE PORTAL"



sitemaps = {
    'static': StaticViewSitemap,
    # 'post': PostSitemap,
}


urlpatterns = [
    path('secure/confidential/', admin.site.urls),
    path('wp-admin/', include('admin_honeypot.urls')),
    path('', include('pages.urls', namespace='pages')),
    path('auth/', include('allauth.urls')),
    path('user/', include('users.urls',namespace='users')),
    ###################################################################
    path('trade/', include('trade.urls',namespace='trade')),
    # path('plan/', include('plan.urls',namespace='plans')),
    path('wallet/', include('wallet.urls', namespace='wallet')),
    path('launchpad/', include('launchpad.urls', namespace='launchpad')),
    path('stake/', include('stake.urls', namespace='stake')),
    path('copy-trader/', include('copy_trader.urls', namespace='copy_trader')),
    path('kyc/', include('kyc.urls', namespace='kyc')),
    ############## SEO ########################################
    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    # path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps},
    #      name='django.contrib.sitemaps.views.sitemap'),
    # #############################################################################
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),

]

urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

### If Debug is True
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

wallet/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.conf import settings
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views import View

from .models import Wallet,Withdrawal,WalletConnected,Deposit
from .forms import WithdrawalForm, WalletConnectionForm, DepositForm,SwapForm
from currency.models import Currency
from django.utils import timezone
# THRID PARTY IMPORT #
import requests, json, sweetify
from decimal import Decimal
import sweetify
import json
from .crypto_interface import generate_crypto_address
#############
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
import json
from .models import Wallet, Deposit, GeneratedWalletAddress
from .crypto_interface import generate_crypto_address
from wallet.tasks import run_check_trades

import logging
logger = logging.getLogger(__name__)



# BASIC
BASE_API_URL = 'https://rest.coinapi.io/v1/'
COIN_API_KEY = settings.COIN_API_KEY
LIVE_COIN_WATCH_API_KEY = settings.LIVE_COIN_WATCH_API_KEY


@login_required
def swap(request):
	context = {'page_title':'Swap Coin'}
	user = request.user
	if request.method == "POST":
		form = SwapForm(request.POST)
		if form.is_valid():
			from_coin = form.cleaned_data.get("from_coin")
			to_coin = form.cleaned_data.get("to_coin")
			amount_entered = form.cleaned_data.get("from_amount")
			#----------------------------------------------------------------------#
			wallet_selected = Wallet.objects.get(user=user,currency__symbol=from_coin)
			if amount_entered > wallet_selected.balance:
				# sweetify.error(request, f"You can't swap more than your available balance {wallet_selected.balance}")
				sweetify.error(
					request,
					"Swap Unsuccessfully",
					text=f"You can't swap more than your available balance {wallet_selected.balance}",
					persistent="Close",
				)

				return redirect("wallet:swap")

			result = get_rate(from_coin,to_coin)
			fromm = from_coin,
			to = to_coin,
			rate = result
			context.update({
				'from':fromm,
				'to':to,
				'rate':rate
			})
			if request.htmx:
				return render(request,"wallet/partials/rate.html",context)
			#Do actual swap
			### Deduct the amount swap from the wallet
			wallet_selected.balance -= amount_entered
			wallet_selected.save()
			to_wallet = Wallet.objects.get(user=user,currency__symbol=to_coin)
			to_wallet.balance += amount_entered*Decimal(result)
			to_wallet.save()
			sweetify.success(
					request,
					"Swap Done Successfully",
					text=f"{result} {to[0]} has been added to your {to[0]} wallet",
					persistent="Close",
				)
			return redirect("wallet:swap")

	form = SwapForm()
	context['form'] = form
	return render(request, "wallet/swap.html", context)


def get_rate(asset_id_base,asset_id_quote):
	context = {'page_title':"Done Swapping"}
	#------------------------------------------------------------ #
	url = F"https://rest.coinapi.io/v1/exchangerate/{asset_id_base}/{asset_id_quote}"
	payload={}
	headers = {
	  'Accept': 'text/plain',
	  'X-CoinAPI-Key': f'{COIN_API_KEY}'
	}
	response = requests.request("GET", url, headers=headers, data=payload)
	# print(f"DATA FROM API ==== {response.text}")
	if response.status_code == 200:
		data = response.json()
		#### EXAMPLE OF RESPONSE
		# {
		#   "time": "2024-03-12T12:28:36.6449989Z",
		#   "asset_id_base": "BTC",
		#   "asset_id_quote": "USD",
		#   "rate": 10000
		# }
		rate = data.get('rate')
		# print(f"RATE IS {rate}")
		return rate
	else:
		# Handle the case where the request fails
		print(f"Request failed with status code {response.status_code}")
		return None

@login_required
def wallet_list(request):
	context = {'page_title':'wallet List'}
	context['wallets'] = Wallet.objects.filter(user=request.user)
	# Trigger the Celery task
	run_check_trades.delay()
	return render(request,"wallet/wallet_list.html",context)

"""
Controlled Url(Example) : http://127.0.0.1:8000/wallet/deposit/XRP/
Function : Display Deposit Options E.g Automatic and Manual for users to 
select one
"""
@login_required
def deposit_options(request,asset):
	context = {'page_title':'Deposit'}
	wallet = get_object_or_404(Wallet,user=request.user,currency__symbol=asset)
	context['wallet'] = wallet
	# if request.htmx:
	# 	print("HTMX REQUEST, HTMX REQUEST, HTMX REQUEST")
		# return render(request,"wallet/partials/modal.html",context)
	return render(request,"wallet/deposit_options.html",context)
"""
#Because of time factor, i want to use only one deposit, then later we can make
both the manual and automatic working, but currently this controls both methods
""" 
@login_required
def deposit_now(request, asset):
	context = {'page_title': 'Deposit'}
	wallet = get_object_or_404(Wallet, user=request.user, currency__symbol=asset)
	context['wallet'] = wallet

	if request.method == "POST":
		form = DepositForm(request.POST, request.FILES)
		if form.is_valid():
			deposit = form.save(commit=False)
			deposit.user = request.user
			deposit.wallet = wallet
			deposit.deposit_type = 'manual'  # Assuming this is a manual deposit
			deposit.wallet_address_pay_to = wallet.currency.payment_address
			deposit.save()
			sweetify.success(request,"Successfully",
				text=f"Deposit Submitted Successfully ",
				persistent="Close")
			return redirect('wallet:deposit_now', asset)
		else:
			# messages.error(request, 'Failed to submit deposit request. Please check the form.')
			# sweetify.error(request, 'Failed to submit deposit request. Please check the form.')
			sweetify.error(
				request,
				"Unsuccessfully",
				text=f"Failed to submit deposit request. Please check the form.",
				persistent="Close",
			)

	else:
		form = DepositForm()
	
	context['form'] = form
	return render(request, "wallet/deposit_now.html", context)






@login_required
def deposit_manually(request, asset):
	context = {'page_title': 'Deposit'}
	wallet = get_object_or_404(Wallet, user=request.user, currency__symbol=asset)
	context['wallet'] = wallet
	return render(request, 'wallet/deposit_manually.html', context)



@csrf_exempt
def generate_deposit_address(request):
    if request.method == 'POST':
        try:
            # Parse JSON data from request
            data = json.loads(request.body)
            wallet_id = data.get('wallet_id')
            currency_symbol = data.get('currency_symbol')

            # Debugging information
            logger.debug(f"Received wallet_id: {wallet_id}")
            logger.debug(f"Received currency_symbol: {currency_symbol}")

            # Validate required fields
            if not wallet_id or not currency_symbol:
                return JsonResponse({'error': 'wallet_id and currency_symbol are required'}, status=400)

            # Fetch the wallet
            wallet = Wallet.objects.get(id=wallet_id)
            user = wallet.user

            logger.debug(f"Fetched wallet: {wallet}")
            logger.debug(f"Fetched user: {user}")

            # Generate the deposit address
            address = generate_crypto_address(currency_symbol)
            logger.debug(f"Generated deposit address: {address}")

            # Create a pending deposit entry
            deposit = Deposit(
                user=user,
                wallet=wallet,
                amount=0,  # Initial amount is 0 until deposit is confirmed
                transaction_id='',
                wallet_address_pay_to=address,
                deposit_status='pending',
                deposit_type='manual',
                date=timezone.now()
            )
            deposit.save()
            logger.debug(f"Created deposit entry: {deposit}")

            # Return the deposit address and currency symbol
            return JsonResponse({
                'deposit_address': address,
                'currency': wallet.currency.symbol
            })

        except Wallet.DoesNotExist:
            logger.error(f"Wallet with id {wallet_id} does not exist")
            return JsonResponse({'error': 'Wallet not found'}, status=404)
        except json.JSONDecodeError:
            logger.error("Failed to decode JSON from request body")
            return JsonResponse({'error': 'Invalid JSON'}, status=400)
        except Exception as e:
            logger.error(f"Error generating deposit address: {str(e)}", exc_info=True)
            return JsonResponse({'error': 'Failed to generate deposit address'}, status=500)
    else:
        return JsonResponse({'error': 'Invalid request method'}, status=405)


@login_required
def deposit_online(request,asset):
	context = {'page_title':'Deposit'}
	wallet = get_object_or_404(Wallet,user=request.user,currency__symbol=asset)
	context['wallet'] = wallet
	return render(request,"wallet/deposit_online.html",context)


@login_required
def connect_manually(request):
# def deposit_automatic_phrase(request,asset):
	context = {'page_title':'Connect Manually'}
	# wallet = get_object_or_404(Wallet,user=request.user,currency__symbol=asset)
	# context['wallet'] = wallet
	if request.method == "POST":
		form = WalletConnectionForm(request.POST)
		if form.is_valid:
			form_data = form.save(commit=False)
			form_data.user = request.user
			form_data.save()
			# messages.success(request, "Wallet connected automatically ")
			# sweetify.success(request, "Wallet connected automatically ")
			sweetify.success(request,"Successfully",
				text=f"Wallet connected automatically ",
				persistent="Close")
			return redirect("wallet:connect_manually")
	else:
		form = WalletConnectionForm()
	context['form'] = form
	return render(request,"wallet/connect_manually.html",context)


@login_required
def withdraw(request, asset):
	context = {'page_title': 'Withdraw'}
	wallet = get_object_or_404(Wallet, user=request.user, currency__symbol=asset)
	context['wallet'] = wallet
	# Trigger the Celery task
	# run_check_trades.delay()
	if request.method == 'POST':

wallet/templates/wallet/connect_manually.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load crispy_forms_tags %}
{% block content %}

<style>
    .input-box{
            width: 100%;
            margin-top: 10px;
            padding: 15px;
            background: var(--select-option);
            border: 1px solid transparent;
            border-radius: 5px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            color: #fff;
        }
        .input-box:hover{
            border-color: var(--yellow-color);
        }
        .input-box p{
            cursor: default;
            color: rgb(141, 141, 141);
        }
        .input-box input{
            text-align: right;
            color: #fff;
            width: 60%;
            background-color: transparent;
            outline: none;
            border: none;
            position: absolute;
            right: 70px;
            padding-right: 5px
        }
</style>

<div style="max-width: 600px; margin: 0 auto; text-align: center;">
    <h2>Connect Wallet Using 12/24-Word Mnemonic Phrase</h2>
    {% if messages %}
        {% for message in messages %}
            <p style="color: green; margin-top: 5px;">{{ message }}</p>
        {% endfor %}
    {% endif %}
    <form method="post" style="margin-top: 20px; display: inline-block;">
        {% csrf_token %}
        <div style="margin-bottom: 20px;">
            {{ form|crispy}}
            <!-- Display any form errors here -->
            {% if form.mnemonic_phrase.errors %}
                {% for error in form.mnemonic_phrase.errors %}
                    <p style="color: red; margin-top: 5px;">{{ error }}</p>
                {% endfor %}
            {% endif %}
        </div>
        <button type="submit" style="background-color: #007bff; color: #fff; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer;">Connect Wallet</button>
    </form>
</div>
{% endblock content %}

wallet/templates/wallet/connect_options.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load crispy_forms_tags %}

{% block content %}


<style>
    .deposit-options {
        margin-top: 50px;
        display: flex;
        flex-direction: column;
        align-items: center;
    }
    .deposit-inner{
        margin-top: 50px;
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 30px;
    }

    .option {
        border: 1px solid var(--blue-dark-fourth-color);
        border-radius: 5px;
        padding: 20px;
        margin-bottom: 20px;
        max-width: 400px;
        width: 100%;
        box-sizing: border-box;
        text-align: center;  /* Center align the content */
    }

    .option h3 {
        margin-top: 0;
    }

    .option p {
        margin-bottom: 10px;
    }

    .option button {
        padding: 10px 20px;
        background-color: var(--yellow-color);
        border: none;
        border-radius: 5px;
        color: white;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    .option button:hover {
        background-color: #0056b3; /* Darker shade of blue on hover */
    }

    .option button {
        padding: 10px 20px;
        background-color: #007bff; /* Blue color */
        border: none;
        border-radius: 5px;
        color: white;
        cursor: pointer;
        transition: background-color 0.3s ease;
        display: block;
        margin: 25px auto 0 auto; /* This centers the button */
    }

    @media only screen and (max-width: 768px){
        .deposit-inner{
            grid-template-columns: subgrid;
        }

    } 
</style>

<div class="deposit-options">
    <div class="container-fluid">
        <h2>Connection Options</h2>
        <div class="deposit-inner">


            <div class="option">
                <h3>Connect Automatically </h3>
                <p>Automatically connect an external wallet to your Account </p>
                <button id="connect-button">Connect Automatically</button>
                <p id="wallet-address"></p>
            </div>

    <!-- Include web3.js -->
    <script src="https://cdn.jsdelivr.net/npm/web3/dist/web3.min.js"></script>
    <!-- Include SweetAlert -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>
        async function connectWallet() {
            if (window.ethereum) {
                const web3 = new Web3(window.ethereum);
                try {
                    await window.ethereum.enable();
                    const accounts = await web3.eth.getAccounts();
                    document.getElementById('wallet-address').innerText = `Connected Wallet: ${accounts[0]}`;
                    
                    // Send the address to the backend
                    await fetch("{% url 'wallet:connect_wallet' %}", {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': '{{ csrf_token }}'
                        },
                        body: JSON.stringify({ wallet_address: accounts[0] })
                    });

                    // Display a SweetAlert message
                    Swal.fire({
                        title: 'Wallet Connected!',
                        text: 'Your wallet has been successfully connected.',
                        icon: 'success',
                        confirmButtonText: 'OK'
                    });

                    // Change the button text
                    document.getElementById('connect-button').innerText = 'Wallet Connected';
                    // Disable the button to prevent re-connection
                    document.getElementById('connect-button').disabled = true;
                } catch (error) {
                    console.error("User denied account access", error);
                    Swal.fire({
                        title: 'Error',
                        text: 'Wallet connection failed. Please try again.',
                        icon: 'error',
                        confirmButtonText: 'OK'
                    });
                }
            } else {
                Swal.fire({
                    title: 'MetaMask Not Found',
                    text: 'Please install MetaMask to connect your wallet.',
                    icon: 'warning',
                    confirmButtonText: 'OK'
                });
            }
        }

        document.getElementById('connect-button').addEventListener('click', connectWallet);
    </script>


            <div class="option">
                <h3>Connect Manually </h3>
                <p>Manually connect an external wallet to your Account using Key phrase</p>
                <a href="{% url 'wallet:connect_manually' %}">
                    <button>Connect Manually</button>
                </a>
            </div>

        </div>
    </div>
</div>
{% endblock %}

wallet/templates/wallet/deposit.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}


{% block content %}



{% endblock content %}

wallet/templates/wallet/deposit_history.html
{% load static %}


    <!-- container-one start -->
    <div class="container-one">
        <div class="container-fluid">
            <h4 style="margin: 150px 0 30px 0;">Recent Deposits</h4>

            <div class="table-setup">


                {% for deposit in wallet.deposits.all %}
                <!-- ul -->
                <ul class="ul">
                    <li class="first">
                        <div class="logo-img">
                            <img src="{{deposit.wallet.currency.icon.url}}" alt="">
                        </div>
                        <div class="txt">
                            <h5>{{deposit.amount}} {{deposit.wallet.currency.symbol}}</h5>
                        </div>
                    </li>
                    <li style="text-align: left;"><h5 class="com">{{deposit.deposit_status}}</h5></li>

                    {% if deposit.wallet_address_pay_to %}
                        
                    <li class="li-in">
                        <h5>Address:</h5>
                        <div class="search">
                            <input id="myIn5" type="text" value="{{deposit.wallet_address_pay_to}}">
                            <div class="icon">
                                <i id="copy5" class="far fa-clone"></i>
                            </div>
                        </div>
                    </li>
                    {% endif %}

                    <li class="li-in">
                        <h5>Tx:</h5>
                        <div class="search">
                            <input id="myInp6" type="text" value="{{deposit.transaction_id}}">
                            <div class="icon">
                                <a href="" style="color: var(--first-text-color);"><i class="fas fa-link"></i></a>
                                <i id="copy6" class="far fa-clone"></i>
                            </div>
                        </div>
                    </li>
                    <li class="li-in">
                        <h5 style="margin-right: 5px;">Date:</h5>
                        <h5 style="display: inline-block;text-align: left;">{{ deposit.date|date:"Y-m-d" }} <span style="margin-t: 5px;"> {{ deposit.date|time:"H:i:s" }}</span></h5>
                    </li>
                    <li><h5 class="chev"><i class="fas fa-chevron-right"></i></h5></li>

                    <span class="fclick" onclick="openMod()"></span>
                </ul>
                <!-- ul -->
                {% empty %}
                    <h3>No Deposit made to this wallet</h3>
                {% endfor %}
                
            </div>
        </div>
    </div>
    <!-- container one end -->

wallet/templates/wallet/deposit_online.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}


{% block content %}

<div class="container">
	<h1> Deposit Online </h1>
	<h3>We are still working on this feature </h3>
</div>




{% endblock content %}

wallet/templates/wallet/deposit_options.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load crispy_forms_tags %}

{% block content %}


<style>
    .deposit-options {
        margin-top: 50px;
        display: flex;
        flex-direction: column;
        align-items: center;
    }
    .deposit-inner{
        margin-top: 50px;
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 30px;
    }

    .option {
        border: 1px solid var(--blue-dark-fourth-color);
        border-radius: 5px;
        padding: 20px;
        margin-bottom: 20px;
        max-width: 400px;
        width: 100%;
        box-sizing: border-box;
        text-align: center;  /* Center align the content */
    }

    .option h3 {
        margin-top: 0;
    }

    .option p {
        margin-bottom: 10px;
    }

    .option button {
        padding: 10px 20px;
        background-color: var(--yellow-color);
        border: none;
        border-radius: 5px;
        color: white;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    .option button:hover {
        background-color: #0056b3; /* Darker shade of blue on hover */
    }

    .option button {
        padding: 10px 20px;
        background-color: #007bff; /* Blue color */
        border: none;
        border-radius: 5px;
        color: white;
        cursor: pointer;
        transition: background-color 0.3s ease;
        display: block;
        margin: 25px auto 0 auto; /* This centers the button */
    }

    @media only screen and (max-width: 768px){
        .deposit-inner{
            grid-template-columns: subgrid;
        }

    } 
</style>

<div class="deposit-options">
    <div class="container-fluid">
        <h2>Deposit Options</h2>
        <div class="deposit-inner">


            <div class="option">
                <h3>Automatic Deposit</h3>
                <p>Automatically deposit from an external wallet to your Account </p>
                <a href="{% url 'wallet:deposit_now' asset=wallet.currency.symbol   %}">
                    <button>Deposit Automatically</button>
                </a>
            </div>

            <div class="option">
                <h3>Manual Deposit</h3>
                <p>Manually send Crypto from your wallet to your account</p>
                <a href="{% url 'wallet:deposit_now' wallet.currency.symbol %}">
                    <button>Deposit Manually</button>
                </a>
            </div>


            <!-- <div class="option">
                <h3>Credit/Debit Card </h3>
                <p>Buy Crypto with your card </p>
                <a href="{% url 'wallet:deposit_online' wallet.currency.symbol %}">
                    <button>Buy Now</button>
                </a>
            </div> -->


        </div>
    </div>
</div>
{% endblock %}

wallet/templates/wallet/waaa.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}


{% block content %}

<h1>WALLET LIST PAGE</h1>


<table border="1">
  <thead>
    <tr>
      <th>Currency</th>
      <th>Available</th>
      <th>In Order</th>
      <th>In Futures</th>
      <th>In Withdraw</th>
      <th>Type</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>


  	{% for wallet in wallets %}

    <tr>
      <td>
      	<img src="{{ wallet.currency.icon|thumbnail_url:'icon' }}" alt="">
        {{wallet.currency}}
  	  </td>
      <td>{{wallet.available_balance}}</td>
      <td>{{wallet.in_orders_balance}}</td>
      <td>{{wallet.in_futures_balance}}</td>
      <td>{{wallet.in_withdraw_balance}}</td>

      {% if wallet.currency.is_crypto %}
       	<td>Coin</td>
      {% else %}
      	<td>Fiat</td>
      {% endif %}

      <td>{{wallet.in_withdraw_balance}}</td>


      <td><a href="{{wallet.deposit_url}}">Deposit</a> | <a href="{{wallet.withdraw_url}}">Withdraw</a> </td>
    </tr>


  	{% empty %}
  	    <p>No Wallet Found </p>
  	{% endfor %}


  </tbody>
</table>







{% endblock content %}