kyc/urls.py
from django.urls import path
from . import views
app_name= "kyc"

urlpatterns = [
    path('kyc/', views.kyc_form, name='kyc_form'),
]

stake/urls.py
from django.urls import path
from . import views

app_name = "stake"

urlpatterns = [
	path('available-coin/', views.available_coin,
		name='available_coin'),
	##### We set my_staking as True and pass into the url
	path('my-staking/', views.available_coin, 
		{'my_staking': True},name='my_staking'),
	path('<str:coin_symbol>/stake-now/', views.stake_now,name='stake_now'),
]

website/urls.py
from django.contrib import admin
from django.urls import path,include
# from django.urls import re_path as url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

############### SITEMAP #################################
from django.contrib.sitemaps.views import sitemap
from seo.sitemaps import StaticViewSitemap



admin.site.site_header = " TRADE XSPHERE "
admin.site.site_title = "TRADE XSPHERE  ADMIN PORTAL"
admin.site.index_title = "WELCOME TO TRADE XSPHERE PORTAL"



sitemaps = {
    'static': StaticViewSitemap,
    # 'post': PostSitemap,
}


urlpatterns = [
    path('secure/confidential/', admin.site.urls),
    path('wp-admin/', include('admin_honeypot.urls')),
    path('', include('pages.urls', namespace='pages')),
    path('auth/', include('allauth.urls')),
    path('user/', include('users.urls',namespace='users')),
    ###################################################################
    path('trade/', include('trade.urls',namespace='trade')),
    # path('plan/', include('plan.urls',namespace='plans')),
    path('wallet/', include('wallet.urls', namespace='wallet')),
    path('launchpad/', include('launchpad.urls', namespace='launchpad')),
    path('stake/', include('stake.urls', namespace='stake')),
    path('copy-trader/', include('copy_trader.urls', namespace='copy_trader')),
    path('kyc/', include('kyc.urls', namespace='kyc')),
    ############## SEO ########################################
    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    # path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps},
    #      name='django.contrib.sitemaps.views.sitemap'),
    # #############################################################################
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),

]

urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

### If Debug is True
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

stake/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from currency.models import Currency
from django.contrib.auth import get_user_model
from wallet.models import Wallet

User = get_user_model()



class Duration(models.Model):
	duration_days = models.PositiveIntegerField()
	percentage_return = models.PositiveIntegerField()

	def __str__(self):
		return f"{self.duration_days} Days to give {self.percentage_return}% "


class StakePlan(models.Model):
	coin = models.OneToOneField(
		Currency,
		on_delete=models.CASCADE,
		related_name="coin_stake",
		limit_choices_to={'is_crypto': True}  # Filter currencies with is_crypto=True
	)
	minimum_stake_amount = models.DecimalField(max_digits=20, decimal_places=8)
	maximum_stake_amount = models.DecimalField(max_digits=20, decimal_places=8)
	durations = models.ManyToManyField(Duration)
	active = models.BooleanField(default=True, help_text="Still allow stakers or not")
	created_at = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return f"{self.coin.name} Stake Plan"

	class Meta:
		ordering = ['-created_at']

	def get_absolute_url(self):
		return reverse('stake:stake_now', args=[self.coin.symbol])



	def status_color(self):
		if self.active :
			return "com"
		# elif self.status == "ongoing":
			# return "com-pend"
		else:
			return "com-lim"




class Stake(models.Model):
	## This is same as in the user model

	STAKE_OUTCOME = [
		('win_stakes', 'Win Stakes'),
		('loose_stakes', 'Loose Stakes'),
	]
	
	STAKE_STATUS = [
		('ongoing', 'Ongoing'),
		('lost', 'Lost'),
		('won', 'Won'),
	]

	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="staker")
	stake_plan = models.ForeignKey(StakePlan, on_delete=models.CASCADE, related_name="stakes")
	staking_wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE, related_name="stake_wallet")
	stake_duration = models.ForeignKey(Duration, on_delete=models.CASCADE, related_name="stake_duratin")
	######
	stake_amount = models.DecimalField(max_digits=20, decimal_places=8)
	estimated_return = models.DecimalField(max_digits=20, decimal_places=8,blank=True,null=True)
	stake_status = models.CharField(max_length=50, choices=STAKE_STATUS,default="ongoing") 
	stake_outcome = models.CharField(max_length=50, choices=STAKE_OUTCOME, 
		default='loose_stakes',help_text="Determine if Trader will loose or win stakes", editable=False)
	###########################################################
	start_date = models.DateTimeField(default=timezone.now)
	end_date = models.DateTimeField(null=True, blank=True)

	def __str__(self):
		return f"{self.user.username}'s Stake in {self.stake_plan.coin.name}"


	def status_color(self):
		if self.status == "won":
			return "com"
		elif self.status == "ongoing":
			return "com-pend"
		else:
			return "com-lim"

stake/forms.py
from django import forms
from .models import Stake,Duration

class Stake555Form(forms.ModelForm):
    DURATION_CHOICES = [
        (30, '30 Days'),
        (60, '60 Days'),
        (180, '180 Days'),
        (365, '365 Days'),
    ]

    duration = forms.ChoiceField(choices=DURATION_CHOICES, widget=forms.RadioSelect(attrs={'class': 'blk blk-inner'}))
    stake_amount = forms.DecimalField(widget=forms.TextInput(attrs={'class': 'blk'}))

    class Meta:
        model = Stake
        fields = ['stake_amount', 'duration']

 

class StakeForm(forms.ModelForm):
    duration = forms.ChoiceField(widget=forms.RadioSelect(), label='', required=False)

    class Meta:
        model = Stake
        fields = ['stake_amount', 'duration']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Get all available durations from the Duration model
        durations = Duration.objects.all()
        # Create choices from the durations
        duration_choices = [(duration.duration_days, f"{duration.duration_days} Days") for duration in durations]
        # Update the choices for the duration field
        self.fields['duration'].choices = duration_choices

        # Set placeholder and remove label for stake_amount field
        self.fields['stake_amount'].widget.attrs['placeholder'] = '0.00'
        self.fields['stake_amount'].label = ''

stake/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import StakePlan, Stake
from .forms import StakeForm
from wallet.models import Wallet


import sweetify


@login_required
def available_coin(request, my_staking=None):
	context = {'page_title': 'Available Coin'}
	if my_staking:
		my_staking = Stake.objects.filter(user=request.user)
		context['page_title'] = f"My Staking"
		context['my_staking'] = my_staking
		return render(request,"stake/my_staking.html", context)
	else:
		stake_plans = StakePlan.objects.all()
		# stake_plans = StakePlan.objects.filter(active=True)
		context['stake_plans'] = stake_plans
		return render(request, "stake/available_coin.html", context)



@login_required
def stake_now(request,coin_symbol):
	plan = get_object_or_404(StakePlan,coin__symbol=coin_symbol)
	user_wallet = get_object_or_404(Wallet,user=request.user,
		currency__symbol=coin_symbol)
	form = StakeForm()
	call_command('check_trades')#Management command
	context = {
		'plan': plan,
		'page_title': f'Stake {plan.coin.name}',
		'wallet':user_wallet,
	}
	if request.method == "POST":
		form = StakeForm(request.POST)
		if form.is_valid():
			amount_entered = form.cleaned_data.get("stake_amount")
			duration = form.cleaned_data.get("duration")
			print(f" DURATION {duration}")
			print(f" DURATION {duration}")

			if amount_entered > user_wallet.available_balance:
				sweetify.error(request,f"You can't stake more than your wallet balances {user_wallet.available_balance} {coin_symbol}")
				return redirect("stake:stake_now", coin_symbol)
			
			if amount_entered < plan.minimum_stake_amount:
				sweetify.error(request,f"You can't stake less than the minimum amount {plan.minimum_stake_amount} {coin_symbol}")
				return redirect("stake:stake_now", coin_symbol)
			
			if amount_entered > plan.maximum_stake_amount:
				sweetify.error(request,f"You can't stake more than the maximum amount {plan.maximum_stake_amount} {coin_symbol}")
				return redirect("stake:stake_now", coin_symbol)

			form_data = form.save(commit=False)
			form_data.user = request.user
			form_data.stake_plan = plan
			form_data.staking_wallet = user_wallet

            # # Attach the selected duration to the stake instance
            # selected_duration = Duration.objects.get(duration_days=duration)
            # stake.duration = selected_duration


			form_data.save()
			sweetify.success(request,f"You've stake {amount_entered}{coin_symbol} successfully")
			return redirect("stake:stake_now", coin_symbol)

		else:
			sweetify.error(request,"Something wrong with the form")
			return redirect("stake:stake_now", coin_symbol)

	context['form'] = form
	return render(request, 'stake/stake_now.html', context)


	
	# stake_duration = models.ForeignKey(Duration, on_delete=models.CASCADE, related_name="stake_duratin")

stake/templates/stake/available_coin.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load crispy_forms_tags %}


{% block content %}
    

    <style>
      .filter .filter-inner {
        display: flex;
        justify-content: space-between;
        border-bottom: 1px solid var(--purple-color);
        margin: 50px 0 30px 0;
      }
      .filter .filter-inner li {
        display: inline-block;
        cursor: pointer;
        font-size: 0.9rem;
        margin-right: 15px;
        transition: var(--transition);
        color: var(--first-text-color);
      }
      .filter .filter-inner li::after {
        content: "";
        display: block;
        margin-top: 20px;
        height: 3px;
        width: 0;
        background-color: var(--yellow-color);
        transition: var(--transition);
      }
      .filter .filter-inner li:hover::after,
      .filter .filter-inner li.active::after {
        width: 100%;
      }
      .filter .filter-inner li:hover,
      .filter .filter-inner li.active {
        color: var(--yellow-color);
      }
      .filter .filter-inner .search {
        background-color: transparent;
        display: flex;
        align-items: center;
        border-radius: 20px;
        overflow: hidden;
      }
      .filter .filter-inner .search input {
        width: 100%;
        background-color: transparent;
        outline: none;
        border: none;
        font-size: 0.9rem;
        margin-left: 10px;
        color: var(--first-text-color);
      }
      .filter .filter-inner .search i {
        padding: 10px 15px;
      }
      .container-one .table-setup #spotOne ul{
        grid-template-columns: 2fr 1fr 1fr 1fr 2fr;
        text-align: left;
      }  
      .container-one .table-setup #spotTwo ul{
        grid-template-columns: 2fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr;
        text-align: left;
      }     
      .container-one .table-setup h5.com-lim{
        display: inline-block;
        padding: 4px 30px;
        border-radius: 5px;
        color: var(--red-second-color);
        background-color: #791a2746;
      }      
      .container-one .table-setup h5.com{
        display: inline-block;
        padding: 4px 30px;
        border-radius: 5px;
        color: var(--green-color);
        background-color: #1b6d4b38;
      }
      .container-one .table-setup h5.com-pend{
        display: inline-block;
        padding: 4px 10px;
        border-radius: 5px;
        color: var(--yellow-color);
        background-color: #6d571b38;
      }
      .container-one .table-setup .red{
        display: none;
      }
      .container-one .table-setup h5.one{
        margin-right: 30px;
      }
      .container-one .table-setup h5.tradeL{
        color: var(--yellow-color);
        position: relative;
        display: inline-block; 
        margin-top: 25px;
        z-index: 56;
      }
      .container-one .table-setup h5.two{
        right: 0;
      }
      .pos-ab {
        position: relative;
      }

      @media only screen and (max-width: 992px) {
        .filter .filter-inner {
          border: none;
          flex-direction: column;
        }
        .filter .filter-inner li {
          color: #fff;
          background-color: var(--purple-color);
          padding: 5px;
          border-radius: 5px;
          font-size: 0.8rem;
        }
        .filter .filter-inner li:hover,
        .filter .filter-inner li.active {
          color: #000;
          background-color: var(--yellow-color);
        }
        .filter .filter-inner li::after {
          display: none;
        }
        .filter .filter-inner .search {
          background-color: var(--purple-color);
          margin-top: 20px;
        }
        .container-one .table-setup #spotOne ul{
            grid-template-columns: 100%;

        }
        .container-one .table-setup #spotOne ul li{
          margin-bottom: 40px;
          display: flex;
          align-items: center;
          justify-content: space-between;
        }
        .container-one .table-setup .red{
            display: block;
        }
        .container-one .table-setup .top-tr{
            display: none;
        }
        .container-one .table-setup h5.tradeL{
          position: relative;
          margin-right: 5px;
        }
      }
    </style>

    <!-- container-one start -->
    <div class="container-one">
      <div class="container-fluid">
        <h2>Staking</h2>

        <!-- filter start -->
        <div class="filter">
        	{% include 'stake/stake_nav.html' %}
        <h5 style="margin: 60px 0 40px 0;">* Staking rewards are calculated every day at 00:00 UTC</h5>

        </div>
        <!-- filter end -->

        <!-- table set up start -->
        <div class="table-setup">
          

          <div class="pos-ab">

            <div class="spot">

                <!-- ul -->
                <ul class="top-tr">
                    <li class="first"><p>Coin</p></li>
                    <li><p>Min Amount</p></li>
                    <li><p>Max Amount</p></li>
                    <li><p>Status</p></li>
                    <li><p>Actions</p></li>
                </ul>
                <!-- ul -->

          


              <!-- spot-inner start -->
              <div class="spot-inner">

              	{% for plan in stake_plans %}
                <!-- ul -->
                <ul>
                  <li>
                    <p class="red">Coin</p>
                    <div class="first">
                        <div class="logo-img">
                          <img src="{{plan.coin.icon.url}}" alt="" />
                        </div>
                        <div class="txt">
                          <h5>{{plan.coin.symbol}}</h5>
                          <h6>{{plan.coin.name}}</h6>
                        </div>
                    </div>
                  </li>
                  <li><p class="red">Min Amount</p><h5>{{plan.minimum_stake_amount}}</h5></li>
                  <li><p class="red">Max Amount</p><h5>{{plan.maximum_stake_amount}}</h5></li>
                  <li><p class="red">Status</p><h5 class="{{plan.status_color}}">
                  {% if plan.active %}
                      Active
                  {% else %}
                      In Active
                  
                  {% endif %}
                  
                </h5></li>
                  <li>
                    <p class="red">Actions</p>
                    <div class="tradeL-flex">
                      <h5 class="tradeL one"><a href="{{plan.get_absolute_url}}" style="color: var(--yellow-color);">Read more</a></h5>
                      <h5 class="tradeL"><a href="{{plan.get_absolute_url}}" style="color: var(--yellow-color);">Stake now</a></h5>
                    </div>
                  </li>
                  <a href="{{plan.get_absolute_url}}" class="fclick"></a>
                </ul>
                <!-- ul -->
                {% empty %}
                <!-- ul -->
                <ul>
                  <p>No Coin to Stake on currently</p>
                </ul>
                <!-- ul -->
              	{% endfor %}

              
              </div>
              <!-- spot-inner end -->
            </div>

            
          </div>
        </div>
      </div>
    </div>
    <!-- container one end -->

    
{% endblock content %}

stake/templates/stake/my_staking.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load crispy_forms_tags %}



{% block content %}

    <style>
      .filter .filter-inner {
        display: flex;
        justify-content: space-between;
        border-bottom: 1px solid var(--purple-color);
        margin: 50px 0 30px 0;
      }
      .filter .filter-inner li {
        display: inline-block;
        cursor: pointer;
        font-size: 0.9rem;
        margin-right: 15px;
        transition: var(--transition);
        color: var(--first-text-color);
      }
      .filter .filter-inner li::after {
        content: "";
        display: block;
        margin-top: 20px;
        height: 3px;
        width: 0;
        background-color: var(--yellow-color);
        transition: var(--transition);
      }
      .filter .filter-inner li:hover::after,
      .filter .filter-inner li.active::after {
        width: 100%;
      }
      .filter .filter-inner li:hover,
      .filter .filter-inner li.active {
        color: var(--yellow-color);
      }
      .filter .filter-inner .search {
        background-color: transparent;
        display: flex;
        align-items: center;
        border-radius: 20px;
        overflow: hidden;
      }
      .filter .filter-inner .search input {
        width: 100%;
        background-color: transparent;
        outline: none;
        border: none;
        font-size: 0.9rem;
        margin-left: 10px;
        color: var(--first-text-color);
      }
      .filter .filter-inner .search i {
        padding: 10px 15px;
      } 
      .container-one .table-setup ul{
        grid-template-columns: 2fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr;
        text-align: left;
      }     
      .container-one .table-setup h5.com-lim{
        display: inline-block;
        padding: 4px 30px;
        border-radius: 5px;
        color: var(--red-second-color);
        background-color: #791a2746;
      }      
      .container-one .table-setup h5.com{
        display: inline-block;
        padding: 4px 30px;
        border-radius: 5px;
        color: var(--green-color);
        background-color: #1b6d4b38;
      }
      .container-one .table-setup h5.com-pend{
        display: inline-block;
        padding: 4px 10px;
        border-radius: 5px;
        color: var(--yellow-color);
        background-color: #6d571b38;
      }
      .container-one .table-setup .red{
        display: none;
      }
      .container-one .table-setup h5.one{
        margin-right: 30px;
      }
      .container-one .table-setup h5.tradeL{
        color: var(--yellow-color);
        position: relative;
        display: inline-block; 
        margin-top: 25px;
        z-index: 56;
      }
      .container-one .table-setup h5.two{
        right: 0;
      }
      .pos-ab {
        position: relative;
      }

      @media only screen and (max-width: 992px) {
        .filter .filter-inner {
          border: none;
          flex-direction: column;
        }
        .filter .filter-inner li {
          color: #fff;
          background-color: var(--purple-color);
          padding: 5px;
          border-radius: 5px;
          font-size: 0.8rem;
        }
        .filter .filter-inner li:hover,
        .filter .filter-inner li.active {
          color: #000;
          background-color: var(--yellow-color);
        }
        .filter .filter-inner li::after {
          display: none;
        }
        .filter .filter-inner .search {
          background-color: var(--purple-color);
          margin-top: 20px;
        }
        .container-one .table-setup ul{
            grid-template-columns: 100%;

        }
        .container-one .table-setup ul li{
          margin-bottom: 40px;
          display: flex;
          align-items: center;
          justify-content: space-between;
        }
        .container-one .table-setup .red{
            display: block;
        }
        .container-one .table-setup .top-tr{
            display: none;
        }
        .container-one .table-setup h5.tradeL{
          position: relative;
          margin-right: 5px;
        }
      }
    </style>

    <!-- container-one start -->
    <div class="container-one">
      <div class="container-fluid">
        <h2>Staking</h2>

        <!-- filter start -->
        <div class="filter">
          {% include 'stake/stake_nav.html' %}

          <h5 style="margin: 60px 0 40px 0;">* Staking rewards are calculated every day at 00:00 UTC</h5>

        </div>
        <!-- filter end -->

        <!-- table set up start -->
        <div class="table-setup">
          

          <div class="pos-ab">       

            <div class="future">
              <!-- spot-inner start -->
              <div class="spot-inner">

              <!-- ul -->
                <ul class="top-tr">
                    <li class="first"><p>Coin</p></li>
                    <li><p>Staked</p></li>
                    <li><p>APY</p></li>
                    <li><p>Period</p></li>
                    <li><p>Your reward</p></li>
                    <li><p>Status</p></li>
                    <li><p>Redemption Date</p></li>
                    <li><p>Actions</p></li>
                </ul>
                <!-- ul -->

                <!-- ul -->
                <ul>
                  <li>
                    <p class="red">Coin</p>
                    <div class="first">
                        <div class="logo-img">
                            <img src="images/trx.png" alt="" />
                        </div>
                        <div class="txt">
                            <h5>TRX</h5>
                            <h6>Tron</h6>
                        </div>
                    </div>
                  </li>
                  <li><p class="red">Staked</p><h5>100.00000000</h5></li>
                  <li><p class="red">APY</p><h5>1000.00000000</h5></li>
                  <li><p class="red">Period</p><h5>Active</h5></li>
                  <li><p class="red">Your reward</p><h5>Active</h5></li>
                  <li><p class="red">Status</p><h5 class="com">Active</h5></li>
                  <li><p class="red">Redemption Date</p><h5>01-04-2024</h5></li>
                  <li><p class="red">Actions</p><h5 class="tradeL one"><a href="staking-list.html" style="color: var(--yellow-color);">Read more</a></h5></li>
                </ul>
                <!-- ul -->

                <!-- ul -->
                <ul>
                  <li>
                    <p class="red">Coin</p>
                    <div class="first">
                        <div class="logo-img">
                            <img src="images/trx.png" alt="" />
                        </div>
                        <div class="txt">
                            <h5>TRX</h5>
                            <h6>Tron</h6>
                        </div>
                    </div>
                  </li>
                  <li><p class="red">Staked</p><h5>100.00000000</h5></li>
                  <li><p class="red">APY</p><h5>1000.00000000</h5></li>
                  <li><p class="red">Period</p><h5>Active</h5></li>
                  <li><p class="red">Your reward</p><h5>Active</h5></li>
                  <li><p class="red">Status</p><h5 class="com-pend">Pending</h5></li>
                  <li><p class="red">Redemption Date</p><h5>01-04-2024</h5></li>
                  <li><p class="red">Actions</p><h5 class="tradeL one"><a href="staking-list.html" style="color: var(--yellow-color);">Read more</a></h5></li>
                </ul>
                <!-- ul -->

                <!-- ul -->
                <ul>
                  <li>
                    <p class="red">Coin</p>
                    <div class="first">
                        <div class="logo-img">
                            <img src="images/trx.png" alt="" />
                        </div>
                        <div class="txt">
                            <h5>TRX</h5>
                            <h6>Tron</h6>
                        </div>
                    </div>
                  </li>
                  <li><p class="red">Staked</p><h5>100.00000000</h5></li>
                  <li><p class="red">APY</p><h5>1000.00000000</h5></li>
                  <li><p class="red">Period</p><h5>Active</h5></li>
                  <li><p class="red">Your reward</p><h5>Active</h5></li>
                  <li><p class="red">Status</p><h5 class="com-lim">Inactive</h5></li>
                  <li><p class="red">Redemption Date</p><h5>01-04-2024</h5></li>
                  <li><p class="red">Actions</p><h5 class="tradeL one"><a href="staking-list.html" style="color: var(--yellow-color);">Read more</a></h5></li>
                </ul>
                <!-- ul -->
              </div>
            </div>
            

          </div>
        </div>
      </div>
    </div>
    <!-- container one end -->
{% endblock content %}

stake/templates/stake/stake_nav.html
       <div class="filter-inner">
            <div class="row">
              <a href="{% url 'stake:available_coin' %}"><li {% if page_title == 'Available Coin' %}
                  class="active"
              
              {% endif %} >Available coins</li></a>
              <a href="{% url 'stake:my_staking' %}"><li {% if page_title == 'My Staking' %}
                  class="active"
              
              {% endif %}>My staking</li></a>
            </div>
          </div>